"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

export type Language = "en" | "pt";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined
);

// Translations
const translations = {
  en: {
    // Header
    "nav.features": "Features",
    "nav.examples": "Examples",
    "nav.installation": "Installation",
    "nav.github": "GitHub",
    "nav.contact": "Contact",

    // Hero Section
    "hero.title": "Optimize your React Native screens with AI",
    "hero.subtitle":
      "Let RN AI Optimize analyze your screens and suggest performance improvements powered by AI.",
    "hero.viewNpm": "View on NPM",
    "hero.viewGithub": "View on GitHub",

    // Features Section
    "features.title": "Key Features",
    "features.subtitle":
      "Discover how RN AI Optimize can transform your React Native app development",
    "features.analysis.title": "Automatic Performance Analysis",
    "features.analysis.description":
      "Smart and automatic analysis of your React Native screens to identify performance bottlenecks.",
    "features.ai.title": "AI-Powered Suggestions",
    "features.ai.description":
      "Receive personalized optimization suggestions generated by advanced artificial intelligence.",
    "features.cli.title": "Simple CLI Usage",
    "features.cli.description":
      "Intuitive and easy-to-use command line interface. Just one command to get started.",
    "features.feedback.title": "Instant Feedback",
    "features.feedback.description":
      "Get immediate feedback in your terminal with detailed and actionable analyses.",

    // Example Section
    "example.title": "See It in Action",
    "example.subtitle":
      "Example of how RN AI Optimize analyzes your screens and provides detailed suggestions",
    "example.output": `🔍 Analyzing React Native screens...

📁 Screens found: 5
   • LoginScreen.tsx
   • HomeScreen.tsx
   • ProfileScreen.tsx
   • SettingsScreen.tsx
   • CartScreen.tsx

🤖 AI analysis in progress...

✅ Analysis complete! Suggestions found:

📊 HomeScreen.tsx
   • Move FlatList to React.memo() - Savings: ~15ms
   • Use getItemLayout for better performance
   • Implement optimized keyExtractor

⚡ ProfileScreen.tsx
   • Lazy loading for avatar images
   • Memoize statistics components
   • Reduce re-renders with useCallback

🎯 Total estimated savings: ~45ms per render
💡 Performance score: 8.5/10 → 9.2/10`,

    // Installation Section
    "installation.title": "How to Install",
    "installation.subtitle":
      "Choose the installation method that best fits your workflow",
    "installation.global.title": "Global Installation",
    "installation.global.description": "Install globally to use in any project",
    "installation.global.usage": "Usage:",
    "installation.npx.title": "One-time Use (Recommended)",
    "installation.npx.description": "Run directly without installation",
    "installation.npx.usage": "No prior installation required",
    "installation.recommendation":
      "We recommend using npx to always have the latest version",

    // Footer
    "footer.description":
      "Optimize your React Native applications with the power of artificial intelligence.",
    "footer.links": "Useful Links",
    "footer.npmPackage": "NPM Package",
    "footer.githubRepo": "GitHub Repository",
    "footer.contact": "Contact",
    "footer.quickStart": "Quick Start",
    "footer.quickStartDesc":
      "Run this command in your React Native project directory to get started.",
    "footer.copyright": "© 2024 RN AI Optimize. All rights reserved.",
    "footer.madeWith": "Made with",
    "footer.forCommunity": "for the React Native community",
  },
  pt: {
    // Header
    "nav.features": "Funcionalidades",
    "nav.examples": "Exemplos",
    "nav.installation": "Instalação",
    "nav.github": "GitHub",
    "nav.contact": "Contato",

    // Hero Section
    "hero.title": "Otimize suas telas React Native com IA",
    "hero.subtitle":
      "Deixe o RN AI Optimize analisar suas telas e sugerir melhorias de performance com inteligência artificial.",
    "hero.viewNpm": "Ver no NPM",
    "hero.viewGithub": "Ver no GitHub",

    // Features Section
    "features.title": "Funcionalidades Principais",
    "features.subtitle":
      "Descubra como o RN AI Optimize pode transformar o desenvolvimento das suas aplicações React Native",
    "features.analysis.title": "Análise Automática de Performance",
    "features.analysis.description":
      "Análise inteligente e automática das suas telas React Native para identificar gargalos de performance.",
    "features.ai.title": "Sugestões Powered by IA",
    "features.ai.description":
      "Receba sugestões de otimização personalizadas geradas por inteligência artificial avançada.",
    "features.cli.title": "Uso Simples via CLI",
    "features.cli.description":
      "Interface de linha de comando intuitiva e fácil de usar. Basta um comando para começar.",
    "features.feedback.title": "Feedback Instantâneo",
    "features.feedback.description":
      "Obtenha feedback imediato no seu terminal com análises detalhadas e acionáveis.",

    // Example Section
    "example.title": "Veja em Ação",
    "example.subtitle":
      "Exemplo de como o RN AI Optimize analisa suas telas e fornece sugestões detalhadas",
    "example.output": `🔍 Analisando telas React Native...

📁 Telas encontradas: 5
   • LoginScreen.tsx
   • HomeScreen.tsx
   • ProfileScreen.tsx
   • SettingsScreen.tsx
   • CartScreen.tsx

🤖 Análise de IA em progresso...

✅ Análise concluída! Sugestões encontradas:

📊 HomeScreen.tsx
   • Mover FlatList para React.memo() - Economia: ~15ms
   • Usar getItemLayout para melhor performance
   • Implementar keyExtractor otimizado

⚡ ProfileScreen.tsx
   • Lazy loading para imagens de avatar
   • Memoizar componentes de estatísticas
   • Reduzir re-renders com useCallback

🎯 Economia total estimada: ~45ms por renderização
💡 Score de performance: 8.5/10 → 9.2/10`,

    // Installation Section
    "installation.title": "Como Instalar",
    "installation.subtitle":
      "Escolha o método de instalação que melhor se adapta ao seu fluxo de trabalho",
    "installation.global.title": "Instalação Global",
    "installation.global.description":
      "Instale globalmente para usar em qualquer projeto",
    "installation.global.usage": "Uso:",
    "installation.npx.title": "Uso Único (Recomendado)",
    "installation.npx.description": "Execute diretamente sem instalação",
    "installation.npx.usage": "Não requer instalação prévia",
    "installation.recommendation":
      "Recomendamos usar npx para sempre ter a versão mais recente",

    // Footer
    "footer.description":
      "Otimize suas aplicações React Native com o poder da inteligência artificial.",
    "footer.links": "Links Úteis",
    "footer.npmPackage": "Pacote NPM",
    "footer.githubRepo": "Repositório GitHub",
    "footer.contact": "Contato",
    "footer.quickStart": "Início Rápido",
    "footer.quickStartDesc":
      "Execute este comando no diretório do seu projeto React Native para começar.",
    "footer.copyright": "© 2024 RN AI Optimize. Todos os direitos reservados.",
    "footer.madeWith": "Feito com",
    "footer.forCommunity": "para a comunidade React Native",
  },
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("en"); // English as default

  // Load language from localStorage on mount
  useEffect(() => {
    const savedLanguage = localStorage.getItem("language") as Language;
    if (savedLanguage && (savedLanguage === "en" || savedLanguage === "pt")) {
      setLanguage(savedLanguage);
    }
  }, []);

  // Save language to localStorage when changed
  useEffect(() => {
    localStorage.setItem("language", language);
  }, [language]);

  const t = (key: string): string => {
    return (
      translations[language][
        key as keyof (typeof translations)[typeof language]
      ] || key
    );
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
